# Generated by Django 4.0.3 on 2022-07-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_conversation_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='role',
            new_name='state',
        ),
    ]
